# Generated by Django 4.2 on 2023-04-17 10:29

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to='homes/')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('comment', models.TextField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('rental_period', models.CharField(max_length=50)),
                ('sqft', models.IntegerField()),
                ('name_home', models.CharField(max_length=100)),
                ('owner', models.CharField(max_length=100)),
                ('upload_time', models.IntegerField()),
            ],
        ),
    ]
