# Generated by Django 4.2 on 2023-04-29 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_name_home_home_name_remove_home_comment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='rental_period',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
