# Generated by Django 4.2 on 2023-05-09 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_delete_mymodel_home_owner_en_home_owner_ru_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Happys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
                ('pircture', models.ImageField(upload_to='homese/')),
                ('name', models.CharField(max_length=100)),
                ('jobs', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='home',
            name='owner_en',
        ),
        migrations.RemoveField(
            model_name='home',
            name='owner_ru',
        ),
    ]
